# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_charts', '0004_auto_20200521_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartjsbarmodel',
            name='format_money',
            field=models.BooleanField(default=False, verbose_name='Format for Money'),
        ),
        migrations.AddField(
            model_name='chartjsdoughnutmodel',
            name='format_money',
            field=models.BooleanField(default=False, verbose_name='Format for Money'),
        ),
        migrations.AddField(
            model_name='chartjslinemodel',
            name='format_money',
            field=models.BooleanField(default=False, verbose_name='Format for Money'),
        ),
        migrations.AddField(
            model_name='chartjspiemodel',
            name='format_money',
            field=models.BooleanField(default=False, verbose_name='Format for Money'),
        ),
        migrations.AddField(
            model_name='chartjspolarmodel',
            name='format_money',
            field=models.BooleanField(default=False, verbose_name='Format for Money'),
        ),
        migrations.AddField(
            model_name='chartjsradarmodel',
            name='format_money',
            field=models.BooleanField(default=False, verbose_name='Format for Money'),
        ),
    ]
